apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: us-docker.pkg.dev/emerald-vigil-428902-v5/argo-images/docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]